import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test Drivers</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      {/* quick glance section */}
      <section>
        <div className='flex items-center justify-around my-5 px-24 py-6'>
          {/* glance col */}
          <div className='w-1/2 flex flex-col gap-4'>
            <h2 className='capitalize font-medium text-3xl text-[#129CE9] w-2/3'>
              A quick glance at what Makes us special
            </h2>
            <p className='w-2/3 text-[#6C6969]'>
              LagosRide is a mobility solution that will allow users book and
              share the cost of a ride with similar transit patterns.
            </p>

            <p className='w-2/3 text-[#787777]'>
              It will link users up based on their preferred pick and drop off
              points, each not more than 1km apart respectively, and a pick-up
              time not more than 5mins apart
            </p>
          </div>
          {/* card col */}

          <div className='card  rounded-2xl bg-white max-w-[350px]'>
            <div className='glance-card' />
            <div className='py-6 px-8'>

            <div className='flex items-start gap-3'>
              <div className='bg-[#D92F6C]/20 p-2 rounded-full'>
                <Image
                  src='/img/glanceIcon1.png'
                  width={15}
                  height={15}
                  loading='lazy'
                  className='text-[#d92f6c]'
                  alt='test-logo'
                />
              </div>

              <p className='text-[#6C6969] border-b border-gray-400 pb-5 text-sm w-2/3'>
                Reduces the frequency of &quot; single occupancy Vehicles(SOV)
                &quot; resulting from cheaper fares per trip.
              </p>
            </div>
            <div className='flex items-start gap-3 my-5'>
              <div className='bg-[#D92F6C]/20 p-2 rounded-full'>
                <Image
                  src='/img/glanceIcon1.png'
                  width={15}
                  height={15}
                  loading='lazy'
                  className='text-[#d92f6c]'
                  alt='test-logo'
                />
              </div>

              <p className='text-[#6C6969] border-b border-gray-400 pb-5 text-sm w-2/3'>
              You will now enjoy the comfort of a car ride but pay less
              </p>
            </div>
            <div className='flex items-start gap-3 mt-5'>
              <div className='bg-[#D92F6C]/20 p-2 rounded-full '>
                <Image
                  src='/img/glanceIcon1.png'
                  width={15}
                  height={15}
                  loading='lazy'
                  className='text-[#d92f6c]'
                  alt='test-logo'
                />
              </div>

              <p className='text-[#6C6969] text-sm w-2/3'>
              Drivers will now earn more revenue per trip
              </p>
            </div>
            </div>

           
          </div>
        </div>
      </section>

      {/* car ride section */}
      <section>
        <div className='flex items-center justify-center'>
          <Image src='/img/car.jpg' width={200} height={300} loading='lazy' alt='car'/>
        </div>
      </section>

      <Footer />
    </div>
  );
}
